//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.26 at 04:32:45 PM IST 
//


package xcos;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="bUnsigned" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="line" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="realPart" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="imaginaryPart" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "data")
public class Data {

    @XmlAttribute(name = "bUnsigned")
    protected Boolean bUnsigned;
    @XmlAttribute(name = "column", required = true)
    protected BigInteger column;
    @XmlAttribute(name = "line", required = true)
    protected BigInteger line;
    @XmlAttribute(name = "realPart")
    protected Double realPart;
    @XmlAttribute(name = "imaginaryPart")
    protected Double imaginaryPart;
    @XmlAttribute(name = "value")
    @XmlSchemaType(name = "anySimpleType")
    protected String value;

    /**
     * Gets the value of the bUnsigned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBUnsigned() {
        return bUnsigned;
    }

    /**
     * Sets the value of the bUnsigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBUnsigned(Boolean value) {
        this.bUnsigned = value;
    }

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColumn(BigInteger value) {
        this.column = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLine(BigInteger value) {
        this.line = value;
    }

    /**
     * Gets the value of the realPart property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRealPart() {
        return realPart;
    }

    /**
     * Sets the value of the realPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRealPart(Double value) {
        this.realPart = value;
    }

    /**
     * Gets the value of the imaginaryPart property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getImaginaryPart() {
        return imaginaryPart;
    }

    /**
     * Sets the value of the imaginaryPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setImaginaryPart(Double value) {
        this.imaginaryPart = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
