//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.26 at 03:01:04 PM IST 
//


package xcos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}mxGeometry"/>
 *         &lt;choice>
 *           &lt;element ref="{}BasicBlock"/>
 *           &lt;element ref="{}mxCell"/>
 *         &lt;/choice>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}CommandPort"/>
 *           &lt;element ref="{}ControlPort"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="style" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mxGeometry",
    "basicBlock",
    "mxCell",
    "commandPort",
    "controlPort"
})
@XmlRootElement(name = "CommandControlLink")
public class CommandControlLink {

    @XmlElement(required = true)
    protected MxGeometry mxGeometry;
    @XmlElement(name = "BasicBlock")
    protected BasicBlock basicBlock;
    protected MxCell mxCell;
    @XmlElement(name = "CommandPort")
    protected CommandPort commandPort;
    @XmlElement(name = "ControlPort")
    protected ControlPort controlPort;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String id;
    @XmlAttribute(name = "style")
    @XmlSchemaType(name = "anySimpleType")
    protected String style;

    /**
     * Gets the value of the mxGeometry property.
     * 
     * @return
     *     possible object is
     *     {@link MxGeometry }
     *     
     */
    public MxGeometry getMxGeometry() {
        return mxGeometry;
    }

    /**
     * Sets the value of the mxGeometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link MxGeometry }
     *     
     */
    public void setMxGeometry(MxGeometry value) {
        this.mxGeometry = value;
    }

    /**
     * Gets the value of the basicBlock property.
     * 
     * @return
     *     possible object is
     *     {@link BasicBlock }
     *     
     */
    public BasicBlock getBasicBlock() {
        return basicBlock;
    }

    /**
     * Sets the value of the basicBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicBlock }
     *     
     */
    public void setBasicBlock(BasicBlock value) {
        this.basicBlock = value;
    }

    /**
     * Gets the value of the mxCell property.
     * 
     * @return
     *     possible object is
     *     {@link MxCell }
     *     
     */
    public MxCell getMxCell() {
        return mxCell;
    }

    /**
     * Sets the value of the mxCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link MxCell }
     *     
     */
    public void setMxCell(MxCell value) {
        this.mxCell = value;
    }

    /**
     * Gets the value of the commandPort property.
     * 
     * @return
     *     possible object is
     *     {@link CommandPort }
     *     
     */
    public CommandPort getCommandPort() {
        return commandPort;
    }

    /**
     * Sets the value of the commandPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandPort }
     *     
     */
    public void setCommandPort(CommandPort value) {
        this.commandPort = value;
    }

    /**
     * Gets the value of the controlPort property.
     * 
     * @return
     *     possible object is
     *     {@link ControlPort }
     *     
     */
    public ControlPort getControlPort() {
        return controlPort;
    }

    /**
     * Sets the value of the controlPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlPort }
     *     
     */
    public void setControlPort(ControlPort value) {
        this.controlPort = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

}
