//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.26 at 03:01:04 PM IST 
//


package xcos;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xcos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XcosDiagram_QNAME = new QName("", "XcosDiagram");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xcos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MxCell }
     * 
     */
    public MxCell createMxCell() {
        return new MxCell();
    }

    /**
     * Create an instance of {@link MxGeometry }
     * 
     */
    public MxGeometry createMxGeometry() {
        return new MxGeometry();
    }

    /**
     * Create an instance of {@link Array }
     * 
     */
    public Array createArray() {
        return new Array();
    }

    /**
     * Create an instance of {@link ScilabDouble }
     * 
     */
    public ScilabDouble createScilabDouble() {
        return new ScilabDouble();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link ScilabString }
     * 
     */
    public ScilabString createScilabString() {
        return new ScilabString();
    }

    /**
     * Create an instance of {@link ScilabBoolean }
     * 
     */
    public ScilabBoolean createScilabBoolean() {
        return new ScilabBoolean();
    }

    /**
     * Create an instance of {@link ScilabInteger }
     * 
     */
    public ScilabInteger createScilabInteger() {
        return new ScilabInteger();
    }

    /**
     * Create an instance of {@link MxPoint }
     * 
     */
    public MxPoint createMxPoint() {
        return new MxPoint();
    }

    /**
     * Create an instance of {@link Add }
     * 
     */
    public Add createAdd() {
        return new Add();
    }

    /**
     * Create an instance of {@link SuperBlockDiagram }
     * 
     */
    public SuperBlockDiagram createSuperBlockDiagram() {
        return new SuperBlockDiagram();
    }

    /**
     * Create an instance of {@link MxGraphModel }
     * 
     */
    public MxGraphModel createMxGraphModel() {
        return new MxGraphModel();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link BasicBlock }
     * 
     */
    public BasicBlock createBasicBlock() {
        return new BasicBlock();
    }

    /**
     * Create an instance of {@link CommandPort }
     * 
     */
    public CommandPort createCommandPort() {
        return new CommandPort();
    }

    /**
     * Create an instance of {@link ControlPort }
     * 
     */
    public ControlPort createControlPort() {
        return new ControlPort();
    }

    /**
     * Create an instance of {@link ExplicitInputPort }
     * 
     */
    public ExplicitInputPort createExplicitInputPort() {
        return new ExplicitInputPort();
    }

    /**
     * Create an instance of {@link Orientation }
     * 
     */
    public Orientation createOrientation() {
        return new Orientation();
    }

    /**
     * Create an instance of {@link ExplicitOutputPort }
     * 
     */
    public ExplicitOutputPort createExplicitOutputPort() {
        return new ExplicitOutputPort();
    }

    /**
     * Create an instance of {@link ImplicitInputPort }
     * 
     */
    public ImplicitInputPort createImplicitInputPort() {
        return new ImplicitInputPort();
    }

    /**
     * Create an instance of {@link ImplicitOutputPort }
     * 
     */
    public ImplicitOutputPort createImplicitOutputPort() {
        return new ImplicitOutputPort();
    }

    /**
     * Create an instance of {@link AfficheBlock }
     * 
     */
    public AfficheBlock createAfficheBlock() {
        return new AfficheBlock();
    }

    /**
     * Create an instance of {@link BigSom }
     * 
     */
    public BigSom createBigSom() {
        return new BigSom();
    }

    /**
     * Create an instance of {@link CommandControlLink }
     * 
     */
    public CommandControlLink createCommandControlLink() {
        return new CommandControlLink();
    }

    /**
     * Create an instance of {@link ConstBlock }
     * 
     */
    public ConstBlock createConstBlock() {
        return new ConstBlock();
    }

    /**
     * Create an instance of {@link EventInBlock }
     * 
     */
    public EventInBlock createEventInBlock() {
        return new EventInBlock();
    }

    /**
     * Create an instance of {@link EventOutBlock }
     * 
     */
    public EventOutBlock createEventOutBlock() {
        return new EventOutBlock();
    }

    /**
     * Create an instance of {@link ExplicitInBlock }
     * 
     */
    public ExplicitInBlock createExplicitInBlock() {
        return new ExplicitInBlock();
    }

    /**
     * Create an instance of {@link ExplicitLink }
     * 
     */
    public ExplicitLink createExplicitLink() {
        return new ExplicitLink();
    }

    /**
     * Create an instance of {@link ExplicitOutBlock }
     * 
     */
    public ExplicitOutBlock createExplicitOutBlock() {
        return new ExplicitOutBlock();
    }

    /**
     * Create an instance of {@link GainBlock }
     * 
     */
    public GainBlock createGainBlock() {
        return new GainBlock();
    }

    /**
     * Create an instance of {@link GroundBlock }
     * 
     */
    public GroundBlock createGroundBlock() {
        return new GroundBlock();
    }

    /**
     * Create an instance of {@link ImplicitInBlock }
     * 
     */
    public ImplicitInBlock createImplicitInBlock() {
        return new ImplicitInBlock();
    }

    /**
     * Create an instance of {@link ImplicitLink }
     * 
     */
    public ImplicitLink createImplicitLink() {
        return new ImplicitLink();
    }

    /**
     * Create an instance of {@link ImplicitOutBlock }
     * 
     */
    public ImplicitOutBlock createImplicitOutBlock() {
        return new ImplicitOutBlock();
    }

    /**
     * Create an instance of {@link PrintBlock }
     * 
     */
    public PrintBlock createPrintBlock() {
        return new PrintBlock();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link RoundBlock }
     * 
     */
    public RoundBlock createRoundBlock() {
        return new RoundBlock();
    }

    /**
     * Create an instance of {@link SplitBlock }
     * 
     */
    public SplitBlock createSplitBlock() {
        return new SplitBlock();
    }

    /**
     * Create an instance of {@link Summation }
     * 
     */
    public Summation createSummation() {
        return new Summation();
    }

    /**
     * Create an instance of {@link SuperBlock }
     * 
     */
    public SuperBlock createSuperBlock() {
        return new SuperBlock();
    }

    /**
     * Create an instance of {@link TextBlock }
     * 
     */
    public TextBlock createTextBlock() {
        return new TextBlock();
    }

    /**
     * Create an instance of {@link VoltageSensorBlock }
     * 
     */
    public VoltageSensorBlock createVoltageSensorBlock() {
        return new VoltageSensorBlock();
    }

    /**
     * Create an instance of {@link Mavtyp }
     * 
     */
    public Mavtyp createMavtyp() {
        return new Mavtyp();
    }

    /**
     * Create an instance of {@link MxUndoManager }
     * 
     */
    public MxUndoManager createMxUndoManager() {
        return new MxUndoManager();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mavtyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XcosDiagram")
    public JAXBElement<Mavtyp> createXcosDiagram(Mavtyp value) {
        return new JAXBElement<Mavtyp>(_XcosDiagram_QNAME, Mavtyp.class, null, value);
    }

}
