//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.26 at 03:26:39 PM IST 
//


package mxgraph;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mxgraph package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MxGraphModel_QNAME = new QName("", "mxGraphModel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mxgraph
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MxCell }
     * 
     */
    public MxCell createMxCell() {
        return new MxCell();
    }

    /**
     * Create an instance of {@link MxGeometry }
     * 
     */
    public MxGeometry createMxGeometry() {
        return new MxGeometry();
    }

    /**
     * Create an instance of {@link MxPoint }
     * 
     */
    public MxPoint createMxPoint() {
        return new MxPoint();
    }

    /**
     * Create an instance of {@link MxRectangle }
     * 
     */
    public MxRectangle createMxRectangle() {
        return new MxRectangle();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Mavmx }
     * 
     */
    public Mavmx createMavmx() {
        return new Mavmx();
    }

    /**
     * Create an instance of {@link MxUndoManager }
     * 
     */
    public MxUndoManager createMxUndoManager() {
        return new MxUndoManager();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mavmx }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mxGraphModel")
    public JAXBElement<Mavmx> createMxGraphModel(Mavmx value) {
        return new JAXBElement<Mavmx>(_MxGraphModel_QNAME, Mavmx.class, null, value);
    }

}
